[package]
name = "charlie/endor-temple"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
TableUtil = "sleitnick/table-util@^1"
Comm = "sleitnick/comm@1.0.1"	
Loader = "sleitnick/loader@2.0.0"	
Knit = "sleitnick/knit@^1.7"
Component = "sleitnick/component@2.4.8"
Promise = "evaera/promise@4.0.0"
Cmdr = "evaera/cmdr@1.12.0"
Llama = "shanebutt/llama@1.1.4"
ProfileService = "nidoxs/profileservice@1.0.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.2"